name: 🕵️ Test suite

on:
  push:
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  schedule:
    # Run every Friday at 23:59 UTC
    - cron: 59 23 * * 5

jobs:
  unit-tests:
    # Run unit tests on different version of python
    name: 🐍 Python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ pypy3, 3.6, 3.7, 3.8, 3.9 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python-${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: UnitTests
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        tox

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        file: coverage.xml
        flags: unittests
        name: ${{ matrix.python-version }}

  platform:
    # Check package properly install on different platform (dev setup)
    name: 💻 Platform-${{ matrix.os }}
    needs: [ unit-tests ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Development setup on ${{ matrix.os }}
        run: |
          python -m pip install pip --upgrade
          pip install -e .[dev]
          python -c "import pkg_resources; print(pkg_resources.get_distribution('navmazing').version)"
          python -c "from navmazing import Navigate, NavigateStep, NavigateToSibling, NavigateToAttribute, NavigateToObject"

  package:
    name: ⚙️ Build & Verify Package
    needs: [ unit-tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build and verify with twine
        run: |
          python -m pip install pip twine setuptools wheel --upgrade
          python setup.py sdist bdist_wheel
          ls -l dist
          python -m twine check dist/*
